---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alex.
--- DateTime: 2022/10/20 10:19
---
co = coroutine.wrap(
        function(i)
            print(i)
        end
)
co(1)

c1 = coroutine.create(
        function()
            print(".....")
        end
)

coroutine.resume(c1)

print(coroutine.status(c1))
print(coroutine.running())