---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alex.
--- DateTime: 2022/10/19 10:27
---
if false or nil then
    print("至少有一个true")
else
    print("false和nil都为false")
end

if 0 then
    print("数字0 是 true")
else
    print("数字0 是 false")
end

string1 = "this is string1"
string2 = 'this is string2'

html = [[
<html>
<head></head>
<body>
    <a href="http://www.runoob.com/">菜鸟教程</a>
</body>
</html>
]]

html1 = [=[
 [[[[[这里的字符串可以有这种注释符号，也不影响]]]]]]
]=]

print(string1)
print(string2)
print(html)
print(html1)


--字符串拼接
print("a" .. "b")   --ab
print(175 .. 2153)  --1752153

--求字符串长度
print(#string1)
print(#"this is string1")