---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alex.
--- DateTime: 2022/10/20 10:25
---

t1 = {
    [1] = "1",
    [2] = "2",
    [4] = "4"
}
for i, v in pairs(t1) do
    print(i, v)
end
print("---")
for i, v in ipairs(t1) do
    print(i, v)
end

print("===========")
t2 = {}
t2[1] = "1"
t2[2] = "2"
t2[4] = "4"
for i, v in pairs(t2) do
    print(i, v)
end
print("---")
for i, v in ipairs(t2) do
    print(i, v)
end

print("===========")
t3 = { ["11"] = "1", ["22"] = 2 }
for i, v in pairs(t3) do
    print(i, v)
end
print("---")
for i, v in ipairs(t3) do
    print(i, v)
end

print("===========")
t4 = { key1 = "123", key2 = "456" }
for i, v in pairs(t4) do
    print(i, v)
end
print("---")
for i, v in ipairs(t4) do
    print(i,v)
end


