---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alex.
--- DateTime: 2022/11/11 16:09
---


mymetatable = {}
mytable = setmetatable({key1 = "value1"}, { __newindex = mymetatable })


print(mytable.key1)
print("=====================")

mytable.newkey = "新值2"
print(mytable.newkey)
print(mytable.newkey)
print(mymetatable.key1)
print(mymetatable.newkey)

print("=====================")
mytable.key1 = "新值1"
print(mytable.key1)
print(mymetatable.key1)


