---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alex.
--- DateTime: 2022/10/19 10:10
---
print(type("hello"))
print(type(10.4 * 3))
print(type(print))
print(type(type))
print(type(true))
print(type(nil))
print(type(X))
print(type(type(X)))
print("===========================")


tab1 = { key1 = "val1", key2 = "val2", "val3" }
for i, v in pairs(tab1) do
    print(type(i))
    print(i .. "---" .. v)
end
print("|======================|")

tab1.key1 = nil  --删除表中指定的元素
for i, v in pairs(tab1) do
    print(type(i))
    print(i .. ",,," .. v)
end

print("===")
print(type(X) == nil)       --false
print(type(X) == "nil")     --true


print(type(true))   --boolean
print(type(false))  --boolean
print(type(nil))    --nil
-- 文件末尾注释