---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alex.
--- DateTime: 2022/12/13 11:31
---

ll = {null,1,2}

pp = {}

for k, v in pairs(ll) do
    if v then
        table.insert(pp,v)
    end
end

print(#pp)

xx = {a="b",b="c"}
for i, v in pairs(xx) do
    print(i..v)
end


local s = "%22protocol%22:%22http%22"
pp = string.gsub(s,"%%22","\"")
print(pp)