---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alex.
--- DateTime: 2022/12/13 11:31
---

ll = {null,1,2}

pp = {}

for k, v in pairs(ll) do
    if v then
        table.insert(pp,v)
    end
end

print(#pp)